import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "primary-container": "var(--primary-container)",
        "outline-variant": "var(--outline-variant)",
        "on-background": "var(--on-background)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "background": "var(--background)",
        "error-container": "var(--error-container)",
        "on-error-container": "var(--on-error-container)",
        "surface-dim": "var(--surface-dim)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-surface": "var(--on-surface)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "surface-container-highest": "var(--surface-container-highest)",
        "inverse-primary": "var(--inverse-primary)",
        "surface-container": "var(--surface-container)",
        "tertiary": "var(--tertiary)",
        "outline": "var(--outline)",
        "secondary": "var(--secondary)",
        "primary": {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        "surface-tint": "var(--surface-tint)",
        "inverse-surface": "var(--inverse-surface)",
        "on-primary-container": "var(--on-primary-container)",
        "on-tertiary": "var(--on-tertiary)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "tertiary-container": "var(--tertiary-container)",
        "surface-variant": "var(--surface-variant)",
        "surface": "var(--surface)",
        "secondary-fixed": "var(--secondary-fixed)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "primary-fixed": "var(--primary-fixed)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "on-primary": "var(--on-primary)",
        "surface-container-low": "var(--surface-container-low)",
        "on-secondary": "var(--on-secondary)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-error": "var(--on-error)",
        "secondary-container": "var(--secondary-container)",
        "error": "var(--error)",
        "surface-container-high": "var(--surface-container-high)",
        "on-secondary-container": "var(--on-secondary-container)",
        "surface-bright": "var(--surface-bright)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        foreground: "var(--foreground)",
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "component-gap": "12px",
        "section-margin": "64px",
        unit: "4px",
        "container-padding": "48px",
        "data-grouping": "8px",
      },
      fontFamily: {
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "data-sm": ["JetBrains Mono", "monospace"],
        "data-lg": ["JetBrains Mono", "monospace"],
        "display-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-caps": ["10px", { lineHeight: "1", letterSpacing: "0.2em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "data-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "500" }],
        "data-lg": ["18px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};
export default config;
